export const ADD_FACILITES = "ADD_FACILITES"

export const DELETE_FACILITES = "DELETE_FACILITES"

export const UPDATE_FACILITES = "UPDATE_FACILITES"

export const GET_FACILITES = "GET_FACILITES"

export const ADD_PRODUCTS = "ADD_PRODUCTS"

export const DELETE_PRODUCTS = "DELETE_PRODUCTS"

export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS"

export const GET_PRODUCTS = "GET_PRODUCTS"

export const LOADING_PRODUCT = "LOADINGE_PRODUCT"