export const TOGGL_THEME ="TOGGL_THEME"


export const ADD_CONTACT = "ADD_CONTACT"

export const DELETE_CONTACT = "DELETE_CONTACT"

export const UPDATE_CONTACT = "UPDATE_CONTACT"

export const GET_CONTACT = "GET_CONTACT"

export const LOADING_PRODUCT = "LOADINGE_PRODUCT"